name: Deploy the CONBU

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'

    - name: install
      run: npm install --frozen-lockfile

    - name: build
      run: npm run build


    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

